apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7bop
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-7bop@sha256:a760c731e00d60f078172e35edac1ead3c681f3a78e188de2b7c379d43c1a636
        name: my-nodejs
        resources: {}
status: {}
